version: '3.8'
services:
  angular-app:
    build:
      context: /home/ghada/Documents/AngularProject/CommercialProject/commercial18
    image: angular:v1
    ports:
      - "4200:80"
    volumes:
      - ~/Documents/AngularProject/CommercialProject/commercial18/nginx/default.conf:/etc/nginx/conf.d/default.conf

  commercialapp:
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3306"  # Expose MySQL port 3306 to host port 3307
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    volumes:
      - db-data:/var/lib/mysql  # Persist MySQL data between restarts

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    env_file:
      - .env
    ports:
      - '8090:80'  # Expose phpMyAdmin on port 8090
    environment:
     # PMA_HOST: db  # Connect phpMyAdmin to MySQL container (db service)
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  commercial:
    container_name: commercialcontainer
    build:
      context: .
    image: commercial:v1
    depends_on:
      - commercialapp
    ports:
      - "8081:8081"

networks:
    default:
      external: true
      name: foo

volumes:
  db-data:  # Named volume for MySQL persistence
